### PR TITLE
fix loading babel options for @babel/plugin-proposal-decorators

### LINKED ISSUE #236: Error: Cannot use the decorators and decorators-legacy plugin together
### What steps are needed to reproduce the bug?

1. Create a `.babelrc` which has `@babel/plugin-proposal-decorators`.
2. `npx stylelint "**/*.tsx"` 

### What did you expect to happen?

Errors should be reported by Stylelint.

```
src/App.tsx
 16:9   ✖  Expected "width" to come before "height"        order/properties-order                           
 20:11  ✖  Expected "display" to come before "height"      order/properties-order   
```

### What actually happened?

Nothing. I'm not joking. Nothing happens because `extract.js` ignores Babel's errors.

https://github.com/stylelint/postcss-css-in-js/blob/09af2eb5a1ba41279e099d095c268e170f02e88b/extract.js#L160-L165

Actually, it says:

```
Error: Cannot use the decorators and decorators-legacy plugin together
```

### PR DESCRIPTION
**Pull request by puku0x**
> Which issue, if any, is this issue related to?

Fixes #236 

> Is there anything in the PR that needs further explanation?

This PR solves the problem when `@stylelint/postcss-css-in-js` is used with `.babelrc` which has `@babel/plugin-proposal-decorators` that results the following error.

```
Error: Cannot use the decorators and decorators-legacy plugin together
```

Note the error is not displayed on the console because `extract.js` ignores errors during pursing the babel options.

### CODE REVIEW

**Comment by puku0x** [comment]
@abdonrd Could you approve me running workflows, please?

image

**Comment by puku0x** [comment]
CI needs to be fixed.

image

**Comment by puku0x** [comment]
#240 fixes CI

File: extract.js [hunk 1]
```diff
@@ -151,6 +151,17 @@ function loadBabelOpts(opts) {
...
 	}
 
+	// avoid conflicting with the legacy decorators plugin
+	if (opts.plugins && opts.plugins.findIndex((p) => p.key === 'proposal-decorators') > -1) {
+		const index = opts.parserOpts.plugins.findIndex(
+			(p) => Array.isArray(p) && p[0] === 'decorators',
+		);
+
+		if (index > -1) {
+			opts.parserOpts.plugins.splice(index, 1);
```
Comment (puku0x) [inline extract.js:161]: This removes the following `decorator` plugin to make `loadBabelOpts()` respected user's `.babelrc`.
https://github.com/stylelint/postcss-css-in-js/blob/09af2eb5a1ba41279e099d095c268e170f02e88b/extract.js#L97

**Comment by puku0x** [comment]
CI fixed💪

File: extract.js [hunk 2]
```diff
@@ -151,6 +151,17 @@ function loadBabelOpts(opts) {
 		}
 	}
 
+	// avoid conflicting with the legacy decorators plugin
+	if (opts.plugins && opts.plugins.findIndex((p) => p.key === 'proposal-decorators') > -1) {
```
Comment (ybiquitous) [inline extract.js:155]: [question] It seems the code can be simplified using `some()` as below. What do you think?

```suggestion
	if (opts.plugins && opts.plugins.some((p) => p.key === 'proposal-decorators')) {
```

**Review by ybiquitous — COMMENTED** [review]
@puku0x Thanks for creating the PR! Could you please add a test case for the change?

File: extract.js (hunk 2 above)
Comment (puku0x) [reply extract.js:155]: It looks great!

**Comment by puku0x** [comment]
I'll add a test case for the fix.

**Comment by puku0x** [comment]
Test case added.

File: package.json [hunk 3]
```diff
@@ -74,6 +74,7 @@
     "@babel/core": ">=7.15.5"
   },
   "devDependencies": {
+    "@babel/plugin-proposal-decorators": "^7.16.4",
```
Comment (puku0x) [inline package.json:77]: This babel plugin is needed for the test I added because it loads `@babel/plugin-proposal-decorators` from the generated `.babelrc`.

**Comment by puku0x** [comment]
I confirmed the test case failed without the fix.

image

**Review by ybiquitous — APPROVED** [review]
@puku0x Thank you so much! LGTM 👍🏼

**Comment by ybiquitous** [comment]
@abdonrd Could you please review this pull request if you have time?

**Comment by puku0x** [comment]
I rebased this branch to `master` but it seems `0.37.7` does not solve for the decorators issue without this fix.

**Review by hudochenkov — APPROVED** [review]

**Comment by hudochenkov** [comment]
> - Fixed: silent fail if @babel/plugin-proposal-decorators is in user's Babel configuration ([#237](https://github.com/stylelint/postcss-css-in-js/pull/237))
